name: octopus

services:
  octopus:
    image: mumu-140/octopus-concurrency:v0.10.2-mumu.4
    pull_policy: never
    container_name: octopus
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/yangs/API/octopus/data:/app/data
    environment:
      OCTOPUS_SERVER_HOST: 0.0.0.0
      OCTOPUS_SERVER_PORT: "35276"
